[package]
name = "example-static-react-spa-app"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
graphul = "0.4.0"
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0"
